### PR TITLE
Added Toasted Life Event

### PR DESCRIPTION
**Pull request by arianadavis**

### CODE REVIEW

**Comment by arianadavis** [comment]
@helloayo Hey, just wanted to see if you were able to approve this PR yet. :)

**Comment by helloayo** [comment]
Hey I am only posting free events this year unless you want to work something out (free tickets, affiliate rev share etc.)

**Comment by arianadavis** [comment]
Ah gotcha, is this strictly for Free Afrotech events?, because Booze Cruise you have to pay

**Comment by helloayo** [comment]
No, not strictly free events. Paid events listed either gave me free tickets or did a revenue share.

**Pull request closed without merging**
